import { concepts, services } from '../lib/content';

export default function HomePage() {
  return <main>
    <nav className='nav'><a className='brand' href='/'>CONQUEROR<br /><span>STUDIO</span></a><div className='nav-links'><a href='#work'>Work</a><a href='#craft'>Craft</a><a href='#journal'>Journal</a><a href='#contact'>Contact</a></div><a className='nav-cta' href='#contact'>Free consultation ↗</a></nav>
    <section className='hero'><div className='hero-art'><div className='halo' /><div className='figure' /><span>STUDY 01 · LIGHT / FORM</span></div><div className='hero-copy'><p className='eyebrow'>DIGITAL ATELIER · INDONESIA · 2026</p><h1>We create<br /><em>digital</em><br />masterpieces.</h1><p className='lede'>Timeless digital experiences and intelligent systems for ambitious modern brands.</p><a className='primary-cta' href='#contact'>Begin a conversation ↗</a></div><p className='scroll-note'>SCROLL TO EXPLORE ↓</p></section>
    <section className='section-grid manifesto'><p className='section-number'>01 / PHILOSOPHY</p><div><p className='quote'>Great design should be remembered.<br />Great systems should be invisible.</p><p className='lede'>We believe technology should amplify craftsmanship, not replace it. Every project begins with a blank canvas and ends with something useful, distinctive, and built to last.</p></div></section>
    <section id='work' className='section-grid'><div><p className='section-number'>02 / SELECTED WORK</p><h2>A living<br /><em>archive.</em></h2></div><div className='project-list'>{concepts.map((item) => <article className='project-card' key={item.number}><div className='project-image'><span>CONCEPT<br />ARCHIVE</span></div><p className='section-number'>{item.category} · {item.year}</p><h3>{item.title}</h3><p className='lede'>{item.summary}</p></article>)}</div></section>
    <section id='craft' className='section-grid'><p className='section-number'>03 / OUR CRAFT</p><div className='service-list'>{services.map((service) => <article className='service-row' key={service.number}><span>{service.number}</span><h3>{service.title}</h3><p>{service.description}</p><span>↗</span></article>)}</div></section>
    <section id='journal' className='section-grid journal'><p className='section-number'>04 / JOURNAL</p><div><h2>Notes from<br /><em>the atelier.</em></h2><p className='lede'>Thoughts on digital presence, thoughtful design, and invisible systems.</p><span className='section-number'>FIRST EDITION · COMING SOON</span></div></section>
    <section id='contact' className='contact'><p className='eyebrow'>05 / BEGIN A PROJECT</p><h2>Your vision deserves<br /><em>a digital masterpiece.</em></h2><p className='lede'>Tell us what you are building. We will help you find the clearest next step.</p><a className='primary-cta light' href='https://wa.me/6281295919621'>Start a conversation ↗</a></section>
    <footer className='footer'><div><p className='brand'>CONQUEROR<br /><span>STUDIO</span></p><p className='footer-note'>Crafted in Indonesia.<br />Inspired by Renaissance.<br />Powered by Technology.</p></div><div className='footer-links'><a href='mailto:conqueror.agency404@gmail.com'>Email</a><a href='https://instagram.com/conqueror.404'>Instagram</a><a href='https://wa.me/6281295919621'>WhatsApp</a></div><p className='footer-note'>© 2026 CONQUEROR STUDIO</p></footer>
  </main>;
}
